config/routes.rb
Rails.application.routes.draw do
  resources :items
  resources :shelves
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # HOME
  root    'static_pages#home'

  # SESSIONS
  get     '/login',  to: 'sessions#new'
  post    '/login',  to: 'sessions#create'
  delete  '/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  validates :name, presence: true
end

app/models/shelf.rb
class Shelf < ApplicationRecord
  has_many :items

  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
	has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def index
    @items = Item.all
  end

  def show
  end

  def new
    @item = Item.new
  end

  def edit
  end

  def create
    @shelf = Shelf.find_by(id: params[:item][:shelf_id])
    @items = Item.where(shelf_id: params[:item][:shelf_id])

    if @items.nil? or (!@shelf.nil? and @items.count < @shelf.capacity)
      params[:item][:status] = 'SHELVED'
    else
      params[:item][:shelf_id] = 0
      params[:item][:status] = 'NO SHELF'
    end

    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    if @item.status == 'NO SHELF'
      @shelf = Shelf.find_by(id: params[:item][:shelf_id])
      @items = Item.where(shelf_id: params[:item][:shelf_id])
      
      if @items.nil? or (!@shelf.nil? and @items.count < @shelf.capacity)
        params[:item][:status] = 'SHELVED'
      else
        params[:item][:shelf_id] = 0
        params[:item][:status] = 'NO SHELF'
      end
    elsif @item.status == 'SHELVED'
      params[:item][:status] = 'BORROWED'
      params[:item][:date_of_return] = nil
    elsif @item.status == 'BORROWED' and
      !@item.date_borrowed.nil?
      params[:item][:status] = 'SHELVED'
    end

    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_item
      @item = Item.find(params[:id])
    end

    def item_params
      params.require(:item).permit(:name, :shelf_id, :status, :borrower_id, :date_borrowed, :date_of_return)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
end

app/controllers/shelves_controller.rb
class ShelvesController < ApplicationController
  before_action :set_shelf, only: [:show, :edit, :update, :destroy]

  def index
    @shelves = Shelf.all
  end

  def show
  end

  def new
    @shelf = Shelf.new
  end

  def edit
  end

  def create
    @shelf = Shelf.new(shelf_params)

    respond_to do |format|
      if @shelf.save
        format.html { redirect_to @shelf, notice: 'Shelf was successfully created.' }
        format.json { render :show, status: :created, location: @shelf }
      else
        format.html { render :new }
        format.json { render json: @shelf.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @shelf.update(shelf_params)
        format.html { redirect_to @shelf, notice: 'Shelf was successfully updated.' }
        format.json { render :show, status: :ok, location: @shelf }
      else
        format.html { render :edit }
        format.json { render json: @shelf.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @shelf.destroy
    respond_to do |format|
      format.html { redirect_to shelves_url, notice: 'Shelf was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_shelf
      @shelf = Shelf.find(params[:id])
    end

    def shelf_params
      params.require(:shelf).permit(:name, :capacity)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :username, :password, :email, :role)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def title(page_title = '')
		base_title = 'KARITE'

		if page_title.empty?
			base_title
		else
			page_title + " | " + base_title
		end
	end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shelves_helper.rb
module ShelvesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: item, local: true) do |form| %>
      <% if item.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

          <ul>
          <% item.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= form.label :name %>
        <%= form.text_field :name, id: :item_name, class: 'form-control' %>
      </div>

      <div class="field">
        <%= form.label :shelf_id %>
        <%= form.number_field :shelf_id, id: :item_shelf_id, class: 'form-control' %>
      </div>

      <div class="field">
        <%= form.label :status %>
        <%= form.select :status,
                     [
                      ['NO SHELF', 'NO SHELF'],
                      ['SHELVED', 'SHELVED'],
                      ['BORROWED', 'BORROWED'],
                      ['RETURNED', 'RETURNED']
                     ],
                     id: :item_status, class: 'form-control'
        %>
      </div>

      <div class="field">
        <%= form.label :borrower_id %>
        <%= form.number_field :borrower_id, id: :item_borrower_id, class: 'form-control' %>
      </div>

      <div class="field">
        <%= form.label :date_borrowed %>
        <%= form.date_select :date_borrowed, id: :item_date_borrowed, class: 'form-control' %>
      </div>

      <div class="field">
        <%= form.label :date_of_return %>
        <%= form.date_select :date_of_return, id: :item_date_of_return, class: 'form-control' %>
      </div>

      <div class="actions">
        <%= form.submit %>
      </div>
    <% end %>
  </div>
</div>

app/views/items/edit.html.erb
<% provide(:title, "Edit Item") %>
<div class="center jumbotron">
  <h1>Edit Item</h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_with(model: @item, local: true) do |form| %>
        <% if @item.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

            <ul>
            <% @item.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="field">
          <%= form.label :name %>
          <%= form.text_field :name, id: :item_name, class: 'form-control', :readonly => true %>
        </div>

        <% if @item[:status] == 'NO SHELF' %>
          <%= form.select :shelf_id,
            Shelf.all.collect { |shelf| shelf.id }, :prompt => 'Select a Shelf ID.', include_blank: true, id: :item_shelf_id, class: 'form-control' %>
        <% else %>
          <div class="field">
            <%= form.label :shelf_id %>
            <%= form.text_field :shelf_id, id: :item_shelf_id, class: 'form-control', :readonly => true %>
          </div>
        <% end %>

        <% if @item[:status] == 'SHELVED' %>
          <div class="field">
            <%= form.label :date_borrowed %>
            <%= form.date_select :date_borrowed, id: :item_date_borrowed, class: 'form-control' %>
          </div>
        <% elsif @item[:status] == 'BORROWED' %>
          <div class="field">
            <%= form.label :date_of_return %>
            <%= form.date_select :date_of_return, id: :item_date_of_return, class: 'form-control' %>
          </div>
        <% end %>

        <div class="actions">
          <%= form.submit %>
        </div>
      <% end %>
    </div>
  </div>

  <%= link_to 'Back', items_path %>
</div>

app/views/items/index.html.erb
<% provide(:title, "Items") %>
<p id="notice"><%= notice %></p>
<div class="center jumbotron">
  <h1>Items</h1>
  <%= link_to 'New Item', new_item_path %>
  <br>
  <table id="items" class="table table-bordered table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Shelf</th>
        <th>Status</th>
        <th>Borrower</th>
        <th>Date Borrowed</th>
        <th>Date of Return</th>
      </tr>
    </thead>

    <tbody>
      <% @items.each do |item| %>
        <tr>
          <td><%= item.name %></td>
          <td><%= item.shelf_id %></td>
          <td><%= item.status %></td>
          <td><%= item.borrower_id %></td>
          <td><%= item.date_borrowed %></td>
          <td><%= item.date_of_return %></td>
          <% if item.status == 'SHELVED' %>
            <td><%= link_to 'Borrow', edit_item_path(item) %></td>
          <% elsif item.status == 'BORROWED' %>
            <td><%= link_to 'Return', edit_item_path(item) %></td>
          <% elsif  item.status == 'NO SHELF' %>
            <td><%= link_to 'Assign', edit_item_path(item) %></td>
          <% end %>
          <td><%= link_to 'Delete', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/items/new.html.erb
<% provide(:title, "New Item") %>
<div class="center jumbotron">
  <h1>New Item</h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_with(model: @item, local: true) do |form| %>
        <% if @item.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

            <ul>
            <% @item.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="field">
          <%= form.label :name %>
          <%= form.text_field :name, id: :item_name, class: 'form-control' %>
        </div>

        <div class="field">
          <%= form.label :shelf_id %>
          <% if @shelves %>
            <%= form.number_field :shelf_id, id: :item_shelf_id, class: 'form-control',
              value: 0, :readonly => true %>
          <% else %>
            <%= form.select :shelf_id,
            Shelf.all.collect { |shelf| shelf.id }, :prompt => 'Select a Shelf ID.', include_blank: true,
            id: :item_shelf_id, class: 'form-control' %>
          <% end %>
        </div>

        <div class="actions">
          <%= form.submit %>
        </div>
      <% end %>
    </div>
  </div>

  <%= link_to 'Back', items_path %>
</div>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>
<% provide(:title, "Item Details") %>
<div class="center jumbotron">
  <h1>Item Details</h1>
  <table id="item" class="table table-bordered table-striped">
    <tr>
      <th>Name</th>
      <td><%= @item.name %></td>
    </tr>
    <tr>
      <th>Shelf</th>
      <td><%= @item.shelf_id %></td>
    </tr>
    <tr>
      <th>Status</th>
      <td><%= @item.status %></td>
    </tr>
    <% if @item.status == 'BORROWED' %>
      <tr>
        <th>Borrower ID</th>
        <td><%= @item.borrower_id %></td>
      </tr>
      <tr>
        <th>Date Borrowed</th>
        <td><%= @item.date_borrowed %></td>
      </tr>
    <% end %>
  </table>
  <br>
  <%= link_to 'Back', items_path %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Created by <a href="https://github.com/kbsamboa/karite">Katrina B. Samboa</a>.
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "KARITE", '/', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
<!--         <% if logged_in? %>
          <li><%= link_to "Users", '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
              <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %> -->
        <li><%= link_to "Items", items_path %></li>
        <li><%= link_to "Shelves", shelves_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag  'application',
                                'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag     'application',
                                media: 'all',
                                'data-turbolinks-track': 'reload' %>
  <!-- JAVASCRIPTS -->
    <%= javascript_include_tag 'https://code.jquery.com/ui/1.11.4/jquery-ui.min.js' %>
    <%= javascript_include_tag 'toastr.min.js' %>
    <%= javascript_include_tag 'bootstrap3-wysihtml5.all.min.js' %>
    <%= javascript_include_tag 'jquery.dataTables.min.js' %>
    <%= javascript_include_tag 'dataTables.bootstrap.min.js' %>
    <%= javascript_include_tag 'jquery.slimscroll.min.js' %>
    <%= javascript_include_tag 'fastclick.js' %>
    <%= javascript_include_tag 'admin-lte-app.min.js' %>
    <%= javascript_include_tag 'icheck.min.js' %>
    <%= javascript_include_tag 'bootstrap-datepicker.js' %>
  <!-- STYLESHEETS -->
    <%= stylesheet_link_tag 'toastr.css' %>
    <%= stylesheet_link_tag 'AdminLTE.min.css' %>
    <%= stylesheet_link_tag 'admin-lte-all-skins.min.css' %>
    <%= stylesheet_link_tag 'blue.css' %>
    <%= stylesheet_link_tag 'dataTables.bootstrap.css' %>
    <%= stylesheet_link_tag 'datepicker3.css' %>

    <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css' %>
    <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/shelves/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: shelf, local: true) do |form| %>
      <% if shelf.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(shelf.errors.count, "error") %> prohibited this shelf from being saved:</h2>

          <ul>
          <% shelf.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= form.label :name %>
        <%= form.text_field :name, id: :shelf_name, class: 'form-control' %>
      </div>

      <div class="field">
        <%= form.label :capacity %>
        <%= form.number_field :capacity, id: :shelf_capacity, class: 'form-control', within: 1..25 %>
      </div>

      <div class="actions">
        <%= form.submit %>
      </div>
    <% end %>
  </div>
</div>

app/views/shelves/edit.html.erb
<h1>Editing Shelf</h1>

<%= render 'form', shelf: @shelf %>

<%= link_to 'Show', @shelf %> |
<%= link_to 'Back', shelves_path %>

app/views/shelves/index.html.erb
<% provide(:title, "Shelves") %>
<p id="notice"><%= notice %></p>
<div class="center jumbotron">
  <h1>Shelves</h1>
  <%= link_to 'New Shelf', new_shelf_path %>
  <br>
  <table id="items" class="table table-bordered table-striped">
    <thead>
      <tr>
      <th>Name</th>
      <th>Capacity</th>
    </tr>
  </thead>

  <tbody>
    <% @shelves.each do |shelf| %>
      <tr>
        <td><%= shelf.name %></td>
        <td><%= shelf.capacity %></td>
        <td><%= link_to 'Delete', shelf, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/shelves/new.html.erb
<% provide(:title, "New Shelf") %>
<div class="center jumbotron">
  <h1>New Shelf</h1>

  <%= render 'form', shelf: @shelf %>

  <%= link_to 'Back', shelves_path %>
</div>

app/views/shelves/show.html.erb
<p id="notice"><%= notice %></p>
<% provide(:title, "Shelf Details") %>
<div class="center jumbotron">
  <h1>Shelf Details</h1>
  <table id="shelf" class="table table-bordered table-striped">
    <tr>
      <th>Name</th>
      <td><%= @shelf.name %></td>
    </tr>
    <tr>
      <th>Capacity</th>
      <td><%= @shelf.capacity %></td>
    </tr>
  </table>
  <br>
  <%= link_to 'Back', shelves_path %>
</div>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>WELCOME!</h1>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username, id: :user_username %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password, id: :user_password %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="field">
    <%= form.label :role %>
    <%= form.text_field :role, id: :user_role %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Username</th>
      <th>Password</th>
      <th>Email</th>
      <th>Role</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.username %></td>
        <td><%= user.password %></td>
        <td><%= user.email %></td>
        <td><%= user.role %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Role:</strong>
  <%= @user.role %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>